server:
  port: 8001
spring:
  rabbitmq:
    host: 192.168.74.128
    port: 5672
    username: guest
    password: guest
    virtual-host: / # 虚拟主机
    listener:
      simple:
        acknowledge-mode: manual # 设置消息手动应答
  mail:
    username: Jay0l1s0214@163.com # 邮箱账号
    password: CSSIYJDZZLEAFSRO # 授权码，需要开启该账号的SMTP服务才可以以代码的显示发送邮件
    host: smtp.163.com # 163邮件的服务器
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/2205myschool?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
logging:
  level:
    com.lss.consumer: debug