server:
  port: 8001
spring:
  rabbitmq:
    host: 192.168.74.128
    port: 5672
    username: guest
    password: guest
    virtual-host: / # 虚拟主机
    listener:
      simple:
        acknowledge-mode: manual # 设置消息手动应答
  redis:
    port: 6379
    host: 127.0.0.1
logging:
  level:
    com.lss.consumer: debug